spring.application.name=tracker
server.port=8080

# The Dynamic URI
# It will use the environment variables MONGO_USER and MONGO_PASS.
# If they aren't found, it will fail safely instead of exposing your credentials.
spring.mongodb.uri=mongodb+srv://${MONGO_USER}:${MONGO_PASS}@authentication.deab6hp.mongodb.net/story_app_db?retryWrites=true&w=majority&appName=authentication